# Welcome to Jekyll!
#

# Site settings
title: "Jackie + Juan"
description: |
    San Bernardino, California

    December 15, 2018
owner: Juan Diaz # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: juan6218@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jackieandjuan.sytes.net" # the base hostname & protocol for your site

google_analytics: UA-126977402-1

social:
  #twitter: https://twitter.com/
  # github: https://github.com/
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
